<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Product;
use App\Models\Vendor;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Eliminar datos existentes
        DB::table('product')->delete();
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        Product::truncate();

        static $cod = 1000;

        // Productos específicos para cada restaurante
        $products = [
            [
                'cod' => $cod++,
                'name' => 'Crunchy Chicken McNuggets',
                'description' => 'Crunchy McNuggets.',
                'price' => 2.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Spicy Chicken McNuggets',
                'description' => 'Spicy McNuggets.',
                'price' => 2.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Salty Chicken McNuggets',
                'description' => 'Salty McNuggets.',
                'price' => 5.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Hot Chicken McNuggets',
                'description' => 'Hot McNuggets.',
                'price' => 2.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cool Combo 1',
                'description' => 'A delicious Menu for you',
                'price' => 9.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cool Combo 2',
                'description' => 'A delicious Menu for you',
                'price' => 7.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cool Combo 3',
                'description' => 'A delicious Menu for you',
                'price' => 6.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cool Wrapper Combo ',
                'description' => 'A delicious Menu for you',
                'price' => 12.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'McFlurry Oreo',
                'description' => 'Delicious Oreo.',
                'price' => 2.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chicken Bites',
                'description' => 'Crunchy Chicken Bytes',
                'price' => 3.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Apple',
                'description' => 'Very Healthy',
                'price' => 9.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Biscoff',
                'description' => 'Delicious Biscoff',
                'price' => 5.99,
                'vendor_email' => 'info@mcdonalds.com',
                'vendor_name' => 'McDonald\'s',
                'vendor_id' => 1,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Alitas de Pollo Ñam',
                'description' => 'Very Spicy',
                'price' => 5.99,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cheese Bites',
                'description' => 'Very Cheesy',
                'price' => 2.99,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Rosty Nuggets',
                'description' => 'Very Rosty',
                'price' => 2.99,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cream Nuggets',
                'description' => 'Very Cream',
                'price' => 6.99,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Whopper Menu',
                'description' => 'A spectacular Whopper menu.',
                'price' => 8.99,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Whopper Economic Menu',
                'description' => 'A spectacular Whopper Economic menu.',
                'price' => 4.99,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Double Crispy Chicken Menu',
                'description' => 'A spectacular Double Crispy Chicken  menu.',
                'price' => 12.99,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Long Chicken Menu',
                'description' => 'A spectacular Long Chicken  menu.',
                'price' => 7.99,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Magnum',
                'description' => 'A spectacular Magnum Ice Cream.',
                'price' => 6.49,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Gofre',
                'description' => 'A spectacular Gofre',
                'price' => 6.49,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Brownie',
                'description' => 'A spectacular Brownie',
                'price' => 3.49,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Vainilla Sundae',
                'description' => 'A spectacular Vainilla Sundae',
                'price' => 1.49,
                'vendor_email' => 'contact@burgerking.com',
                'vendor_name' => 'Burger King',
                'vendor_id' => 2,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cheese Fries',
                'description' => 'Delicious Cheese Fries',
                'price' => 7.49,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Spicy Wings',
                'description' => 'Delicious Spicy Wings',
                'price' => 19.49,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Normal Fries',
                'description' => 'Delicious Salty Fries and Economic',
                'price' => 2.49,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Economic Fries',
                'description' => 'Very Cheap Fries',
                'price' => 1.15,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Hot Cheese Burguer',
                'description' => 'Delicious Hot Cheese Burguer',
                'price' => 8.49,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Egg Burguer',
                'description' => 'Delicious Egg Burguer',
                'price' => 5.49,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Bacon Burguer',
                'description' => 'Delicious Bacon Burguer',
                'price' => 7.99,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chicken Burguer',
                'description' => 'Delicious Chicken Burguer',
                'price' => 6.99,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Milk Dessert',
                'description' => 'A creamy Milk Dessert.',
                'price' => 1.99,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Aquarius',
                'description' => 'A refreshing Aquarius',
                'price' => 0.99,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Fanta',
                'description' => 'A refreshing Fanta',
                'price' => 1.50,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Coca-Cola',
                'description' => 'A refreshing Coca-Cola',
                'price' => 1.99,
                'vendor_email' => 'info@wendys.com',
                'vendor_name' => 'Wendy\'s',
                'vendor_id' => 3,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Bacon Fries',
                'description' => 'Tasty bacon fries.',
                'price' => 2.99,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Spicy Fries',
                'description' => 'Tasty Spicy bacon fries.',
                'price' => 5.99,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chicken Wings',
                'description' => 'Tasty Chicken Wings',
                'price' => 4.99,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Pure',
                'description' => 'Tasty Pure',
                'price' => 2.99,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'KFC Combo 1',
                'description' => 'An Amazing KFC Combo',
                'price' => 12.99,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chicken Burger',
                'description' => 'A delicious Chicken Burguer',
                'price' => 7.49,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'KFC Combo 2',
                'description' => 'An incredible KFC Combo',
                'price' => 12.49,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Veggie Burguer',
                'description' => 'A Tasty Veggie Burguer',
                'price' => 8.49,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Ice Cream of Conguitos',
                'description' => 'A Refreshing Ice Cream of Conguitos',
                'price' => 4.49,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Ice Cream of Oreo',
                'description' => 'A Refreshing Ice Cream of Oreo',
                'price' => 6.99,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Goffre of Oreo',
                'description' => 'A Delicious Goffre of Oreo',
                'price' => 3.99,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'KFC Salad',
                'description' => 'Nice KFC Salad',
                'price' => 1.99,
                'vendor_email' => 'contact@kfc.com',
                'vendor_name' => 'KFC',
                'vendor_id' => 4,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chicken Wings',
                'description' => 'Crunchy Chicken Wings',
                'price' => 4.49,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chicken Fries',
                'description' => 'Crunchy Chicken Wings',
                'price' => 2.49,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Garlic Fries',
                'description' => 'Crunchy Garlic Fries',
                'price' => 4.99,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Spicy Nuggets',
                'description' => 'Crunchy Spicy Nuggets',
                'price' => 7.99,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Pepperoni Pizza',
                'description' => 'A classic pepperoni pizza.',
                'price' => 9.99,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'BBQ Pizza',
                'description' => 'A classic BBQ pizza.',
                'price' => 12.99,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Formaggio Pizza',
                'description' => 'A classic Formaggio pizza.',
                'price' => 11.99,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Bacon and Peperonni Pizza',
                'description' => 'A classic Bacon and Peperonni pizza.',
                'price' => 10.49,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Strawberry Ice Cream ',
                'description' => 'A cold Strawberry Ice Cream.',
                'price' => 3.49,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Coulant',
                'description' => 'A hot Coulant.',
                'price' => 5.49,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chocolate Bites',
                'description' => 'Hot Chocolate Bites.',
                'price' => 1.49,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Chocolate Crunchy Cookies',
                'description' => 'Crunchy Chocolate Cookies.',
                'price' => 8.49,
                'vendor_email' => 'contact@dominos.com',
                'vendor_name' => 'Domino\'s Pizza',
                'vendor_id' => 8,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Spicy Chicken Wings',
                'description' => 'Crunchy Spicy Chicken Wings.',
                'price' => 6.49,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Garlic Bread',
                'description' => 'Delicious garlic bread.',
                'price' => 3.49,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cheese Fingers',
                'description' => 'Delicious cheese fingers',
                'price' => 4.49,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Lipton',
                'description' => 'Refreshing Lipton.',
                'price' => 3.99,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Pepperoni Pizza',
                'description' => 'A classic pepperoni pizza.',
                'price' => 8.99,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => '4 Cheese Pizza',
                'description' => 'Spectacular 4 cheese pizza.',
                'price' => 8.99,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Spicy Pepperoni Pizza',
                'description' => 'A spicy pepperoni pizza.',
                'price' => 12.99,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Roasted Pizza',
                'description' => 'Increible Roasted Pizza.',
                'price' => 12.49,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Chocolate Ice Cream',
                'description' => 'A cold Chocolate Ice Cream.',
                'price' => 2.49,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Giant Chocolate Cookie',
                'description' => 'A Giant Chocolate Cookie.',
                'price' => 1.49,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Sugar Dessert',
                'description' => 'A sweet Sugar Dessert.',
                'price' => 2.49,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Chocolate Magnum Ice Cream',
                'description' => 'A Refreshing Chocolate Magnum Ice Cream.',
                'price' => 2.99,
                'vendor_email' => 'contact@pizzahut.com',
                'vendor_name' => 'Pizza Hut',
                'vendor_id' => 6,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            
            [
                'cod' => $cod++,
                'name' => 'Bao Muc',
                'description' => 'Delicious Bao Muc',
                'price' => 4.99,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Pho Bo',
                'description' => 'Cheap Pho Bo',
                'price' => 1222.99,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Bun Cha',
                'description' => 'Neat Bun Cha',
                'price' => 12.49,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Goi Cuon',
                'description' => 'Spicy Goi Cuon',
                'price' => 11.49,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Bao Vit',
                'description' => 'Tasty Bao Vit',
                'price' => 4.99,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Bao Muc',
                'description' => 'The Special Bao Muc',
                'price' => 4.49,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Ha Cao',
                'description' => 'The Amazing Ha Cao',
                'price' => 7.99,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'My Xao',
                'description' => 'The Supreme My Xao',
                'price' => 4.79,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Ga Xao',
                'description' => 'A Refreshing Ga Xao',
                'price' => 7.49,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Curry Bo',
                'description' => 'A Spicy Curry Bo',
                'price' => 12.49,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Bun Hai San',
                'description' => 'A Mild Bun Hai San',
                'price' => 7.49,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Curry Chay',
                'description' => 'A Salty Curry Chay',
                'price' => 12.49,
                'vendor_email' => 'info@pandaexpress.com',
                'vendor_name' => 'Panda Express',
                'vendor_id' => 19,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chocolate Cookie',
                'description' => 'Crunchy Chocolate Cookie',
                'price' => 4.49,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Milk Dessert',
                'description' => 'Delicious Milk Dessert',
                'price' => 2.49,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Croissant',
                'description' => 'Sweet Croissant',
                'price' => 4.99,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Donut',
                'description' => 'Sugar Donut',
                'price' => 3.49,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Choclate Shaker',
                'description' => 'A Refreshing Chocolate Shaker',
                'price' => 12.49,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Strawberry Shaker',
                'description' => 'A Refreshing Strawberry Shaker',
                'price' => 10.49,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Cacao Shaker',
                'description' => 'A Refreshing Cacao Shaker',
                'price' => 11.99,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Coffee Shaker',
                'description' => 'A Refreshing Coffee Shaker',
                'price' => 10.99,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Salad',
                'description' => 'A Healthy Salad',
                'price' => 3.49,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'cod' => $cod++,
                'name' => 'Black Tea',
                'description' => 'A Relaxing Black Tea',
                'price' => 1.49,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Lemonade',
                'description' => 'A Refreshing Lemonade',
                'price' => 1.49,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Green Tea',
                'description' => 'A Relaxing Green Tea',
                'price' => 2.99,
                'vendor_email' => 'info@starbucks.com',
                'vendor_name' => 'Starbucks',
                'vendor_id' => 11,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],




            [
                'cod' => $cod++,
                'name' => 'Chocolate Ice Cream',
                'description' => 'A cold Chocolate Ice Cream.',
                'price' => 2.49,
                'vendor_email' => 'info@subway.com',
                'vendor_name' => 'Subway',
                'vendor_id' => 5,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Veggie Delight',
                'description' => 'A healthy veggie delight sandwich.',
                'price' => 4.99,
                'vendor_email' => 'info@subway.com',
                'vendor_name' => 'Subway',
                'vendor_id' => 5,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Chocolate Chip Cookie',
                'description' => 'A freshly baked chocolate chip cookie.',
                'price' => 1.49,
                'vendor_email' => 'info@subway.com',
                'vendor_name' => 'Subway',
                'vendor_id' => 5,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Añadir más productos para Pizza Hut

            // Añadir más productos para Taco Bell
            [
                'cod' => $cod++,
                'name' => 'Crunchy Taco',
                'description' => 'A crunchy taco with beef and lettuce.',
                'price' => 1.99,
                'vendor_email' => 'info@tacobell.com',
                'vendor_name' => 'Taco Bell',
                'vendor_id' => 7,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Nachos',
                'description' => 'Nachos with cheese and jalapeños.',
                'price' => 2.99,
                'vendor_email' => 'info@tacobell.com',
                'vendor_name' => 'Taco Bell',
                'vendor_id' => 7,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Churros',
                'description' => 'Sweet churros with cinnamon sugar.',
                'price' => 1.99,
                'vendor_email' => 'info@tacobell.com',
                'vendor_name' => 'Taco Bell',
                'vendor_id' => 7,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Añadir más productos para Chick-fil-A
            [
                'cod' => $cod++,
                'name' => 'Chicken Sandwich',
                'description' => 'A classic chicken sandwich.',
                'price' => 4.99,
                'vendor_email' => 'info@chickfila.com',
                'vendor_name' => 'Chick-fil-A',
                'vendor_id' => 9,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Waffle Fries',
                'description' => 'Crispy waffle fries.',
                'price' => 2.49,
                'vendor_email' => 'info@chickfila.com',
                'vendor_name' => 'Chick-fil-A',
                'vendor_id' => 9,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Milkshake',
                'description' => 'A creamy milkshake.',
                'price' => 3.49,
                'vendor_email' => 'info@chickfila.com',
                'vendor_name' => 'Chick-fil-A',
                'vendor_id' => 9,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Añadir más productos para Dunkin' Donuts
            [
                'cod' => $cod++,
                'name' => 'Glazed Donut',
                'description' => 'A classic glazed donut.',
                'price' => 1.29,
                'vendor_email' => 'contact@dunkindonuts.com',
                'vendor_name' => 'Dunkin\' Donuts',
                'vendor_id' => 10,
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Breakfast Sandwich',
                'description' => 'A delicious breakfast sandwich.',
                'price' => 3.99,
                'vendor_email' => 'contact@dunkindonuts.com',
                'vendor_name' => 'Dunkin\' Donuts',
                'vendor_id' => 10,
                'category' => 'Main Course',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cod' => $cod++,
                'name' => 'Coffee',
                'description' => 'A hot cup of coffee.',
                'price' => 1.99,
                'vendor_email' => 'contact@dunkindonuts.com',
                'vendor_name' => 'Dunkin\' Donuts',
                'vendor_id' => 10,
                'category' => 'Starter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insertar productos específicos en la base de datos
        foreach ($products as $product) {
            Product::create($product);
        }

        /*
        $vendors = Vendor::all();

        foreach ($vendors as $vendor) {
            $vendorId = $vendor->id;
            $vendorDetails = Vendor::find($vendorId);

            Product::factory()->count(6)->create([
                'vendor_id' => $vendorId,
                'vendor_email' => $vendorDetails->email,
                'vendor_name' => $vendorDetails->name,
            ]);
        }
        */

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
